/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proofLayerAttestationsSol from "./ProofLayerAttestations.sol";
export type { proofLayerAttestationsSol };
export type { VerifierRegistry } from "./VerifierRegistry";
