/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VerifierRegistry {
  export type VerifierStruct = {
    operator: AddressLike;
    manifestHash: BytesLike;
    versionHash: BytesLike;
    registeredAt: BigNumberish;
    active: boolean;
  };

  export type VerifierStructOutput = [
    operator: string,
    manifestHash: string,
    versionHash: string,
    registeredAt: bigint,
    active: boolean
  ] & {
    operator: string;
    manifestHash: string;
    versionHash: string;
    registeredAt: bigint;
    active: boolean;
  };
}

export interface VerifierRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getVerifier"
      | "isActiveOperator"
      | "owner"
      | "registerVerifier"
      | "renounceOwnership"
      | "setVerifierActive"
      | "transferOwnership"
      | "verifierForOperator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "VerifierRegistered"
      | "VerifierStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getVerifier",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveOperator",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerVerifier",
    values: [BytesLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifierActive",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifierForOperator",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifierActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifierForOperator",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRegisteredEvent {
  export type InputTuple = [
    verifierId: BytesLike,
    operator: AddressLike,
    manifestHash: BytesLike,
    versionHash: BytesLike
  ];
  export type OutputTuple = [
    verifierId: string,
    operator: string,
    manifestHash: string,
    versionHash: string
  ];
  export interface OutputObject {
    verifierId: string;
    operator: string;
    manifestHash: string;
    versionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierStatusChangedEvent {
  export type InputTuple = [verifierId: BytesLike, active: boolean];
  export type OutputTuple = [verifierId: string, active: boolean];
  export interface OutputObject {
    verifierId: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerifierRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VerifierRegistry;
  waitForDeployment(): Promise<this>;

  interface: VerifierRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getVerifier: TypedContractMethod<
    [verifierId: BytesLike],
    [VerifierRegistry.VerifierStructOutput],
    "view"
  >;

  isActiveOperator: TypedContractMethod<
    [verifierId: BytesLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerVerifier: TypedContractMethod<
    [
      verifierId: BytesLike,
      operator: AddressLike,
      manifestHash: BytesLike,
      versionHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setVerifierActive: TypedContractMethod<
    [verifierId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifierForOperator: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getVerifier"
  ): TypedContractMethod<
    [verifierId: BytesLike],
    [VerifierRegistry.VerifierStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveOperator"
  ): TypedContractMethod<
    [verifierId: BytesLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerVerifier"
  ): TypedContractMethod<
    [
      verifierId: BytesLike,
      operator: AddressLike,
      manifestHash: BytesLike,
      versionHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifierActive"
  ): TypedContractMethod<
    [verifierId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifierForOperator"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRegistered"
  ): TypedContractEvent<
    VerifierRegisteredEvent.InputTuple,
    VerifierRegisteredEvent.OutputTuple,
    VerifierRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VerifierStatusChanged"
  ): TypedContractEvent<
    VerifierStatusChangedEvent.InputTuple,
    VerifierStatusChangedEvent.OutputTuple,
    VerifierStatusChangedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VerifierRegistered(bytes32,address,bytes32,bytes32)": TypedContractEvent<
      VerifierRegisteredEvent.InputTuple,
      VerifierRegisteredEvent.OutputTuple,
      VerifierRegisteredEvent.OutputObject
    >;
    VerifierRegistered: TypedContractEvent<
      VerifierRegisteredEvent.InputTuple,
      VerifierRegisteredEvent.OutputTuple,
      VerifierRegisteredEvent.OutputObject
    >;

    "VerifierStatusChanged(bytes32,bool)": TypedContractEvent<
      VerifierStatusChangedEvent.InputTuple,
      VerifierStatusChangedEvent.OutputTuple,
      VerifierStatusChangedEvent.OutputObject
    >;
    VerifierStatusChanged: TypedContractEvent<
      VerifierStatusChangedEvent.InputTuple,
      VerifierStatusChangedEvent.OutputTuple,
      VerifierStatusChangedEvent.OutputObject
    >;
  };
}
