/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ProofLayerAttestations {
  export type AttestationStruct = {
    claimId: BytesLike;
    subject: AddressLike;
    evidenceHash: BytesLike;
    resultHash: BytesLike;
    policyHash: BytesLike;
    verifierId: BytesLike;
    confidence: BigNumberish;
    verdict: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
    revoked: boolean;
  };

  export type AttestationStructOutput = [
    claimId: string,
    subject: string,
    evidenceHash: string,
    resultHash: string,
    policyHash: string,
    verifierId: string,
    confidence: bigint,
    verdict: bigint,
    createdAt: bigint,
    expiresAt: bigint,
    revoked: boolean
  ] & {
    claimId: string;
    subject: string;
    evidenceHash: string;
    resultHash: string;
    policyHash: string;
    verifierId: string;
    confidence: bigint;
    verdict: bigint;
    createdAt: bigint;
    expiresAt: bigint;
    revoked: boolean;
  };
}

export interface ProofLayerAttestationsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchor"
      | "getAttestation"
      | "isValid"
      | "owner"
      | "pause"
      | "paused"
      | "revoke"
      | "transferOwnership"
      | "unpause"
      | "verifierRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationAnchored"
      | "AttestationRevoked"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchor",
    values: [
      BytesLike,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isValid", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isValid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierRegistry",
    data: BytesLike
  ): Result;
}

export namespace AttestationAnchoredEvent {
  export type InputTuple = [
    claimId: BytesLike,
    subject: AddressLike,
    verifierId: BytesLike,
    evidenceHash: BytesLike,
    resultHash: BytesLike,
    verdict: BigNumberish,
    confidence: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    subject: string,
    verifierId: string,
    evidenceHash: string,
    resultHash: string,
    verdict: bigint,
    confidence: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    claimId: string;
    subject: string;
    verifierId: string;
    evidenceHash: string;
    resultHash: string;
    verdict: bigint;
    confidence: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationRevokedEvent {
  export type InputTuple = [claimId: BytesLike, reason: string];
  export type OutputTuple = [claimId: string, reason: string];
  export interface OutputObject {
    claimId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofLayerAttestations extends BaseContract {
  connect(runner?: ContractRunner | null): ProofLayerAttestations;
  waitForDeployment(): Promise<this>;

  interface: ProofLayerAttestationsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchor: TypedContractMethod<
    [
      claimId: BytesLike,
      subject: AddressLike,
      evidenceHash: BytesLike,
      resultHash: BytesLike,
      policyHash: BytesLike,
      verifierId: BytesLike,
      confidence: BigNumberish,
      verdict: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAttestation: TypedContractMethod<
    [claimId: BytesLike],
    [ProofLayerAttestations.AttestationStructOutput],
    "view"
  >;

  isValid: TypedContractMethod<[claimId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  revoke: TypedContractMethod<
    [claimId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifierRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [
      claimId: BytesLike,
      subject: AddressLike,
      evidenceHash: BytesLike,
      resultHash: BytesLike,
      policyHash: BytesLike,
      verifierId: BytesLike,
      confidence: BigNumberish,
      verdict: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [claimId: BytesLike],
    [ProofLayerAttestations.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValid"
  ): TypedContractMethod<[claimId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<
    [claimId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifierRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AttestationAnchored"
  ): TypedContractEvent<
    AttestationAnchoredEvent.InputTuple,
    AttestationAnchoredEvent.OutputTuple,
    AttestationAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "AttestationRevoked"
  ): TypedContractEvent<
    AttestationRevokedEvent.InputTuple,
    AttestationRevokedEvent.OutputTuple,
    AttestationRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AttestationAnchored(bytes32,address,bytes32,bytes32,bytes32,uint8,uint8,uint64)": TypedContractEvent<
      AttestationAnchoredEvent.InputTuple,
      AttestationAnchoredEvent.OutputTuple,
      AttestationAnchoredEvent.OutputObject
    >;
    AttestationAnchored: TypedContractEvent<
      AttestationAnchoredEvent.InputTuple,
      AttestationAnchoredEvent.OutputTuple,
      AttestationAnchoredEvent.OutputObject
    >;

    "AttestationRevoked(bytes32,string)": TypedContractEvent<
      AttestationRevokedEvent.InputTuple,
      AttestationRevokedEvent.OutputTuple,
      AttestationRevokedEvent.OutputObject
    >;
    AttestationRevoked: TypedContractEvent<
      AttestationRevokedEvent.InputTuple,
      AttestationRevokedEvent.OutputTuple,
      AttestationRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
